frame_body: os_sensor
sensors:
    -  # D455
        topic: /d455/depth/image_rect_raw
        frame: d455_depth_optical_frame
        bins_w: 16
        bins_h: 9
        percentile: 10  # [%]
        min_ratio_per_bin: 0  # [0-1]
        mm_resolution: 1  # mm resolution in 1 pixel unit
        min_range: 0.1  # [m]
        max_range: 10  # [m]
        is_pointcloud: false
        is_polar: false
        cam_info_topic: /d455/depth/camera_info
        # input info (not used since camera_info is used)
        # hfov: 87  # [deg]
        # vfov: 58  # [deg]
        # image_w: 512
        # image_h: 128
    -  # Ouster
        topic: /os_cloud_node/range_image
        frame: os_sensor
        bins_w: 32
        bins_h: 8
        percentile: 10  # [%]
        min_ratio_per_bin: 0  # [0-1]
        mm_resolution: 4  # mm resolution in 1 pixel unit
        min_range: 0.6  # [m]
        max_range: 10  # [m]
        is_pointcloud: false
        is_polar: true
        # input info (since no cam_info is provided)
        azimuth_range: [-180, 180]  # range of azimuth covered by sensor [deg]
        elevation_range: [-45, 45]  # range of azimuth covered by sensor [deg]
        image_w: 512
        image_h: 128
    -  # Airy
        topic: /os_cloud_node/range_image
        frame: os_sensor
        bins_w: 32
        bins_h: 8
        percentile: 10  # [%]
        min_ratio_per_bin: 0  # [0-1]
        mm_resolution: 4  # mm resolution in 1 pixel unit
        min_range: 0.6  # [m]
        max_range: 10  # [m]
        is_pointcloud: true
        is_polar: true
        # input info (since no cam_info is provided)
        azimuth_range: [-180, 180]  # range of azimuth covered by sensor [deg]
        elevation_range: [0, 90]  # range of elevation covered by sensor [deg]
        image_w: 512
        image_h: 192
